CREATE SCHEMA GLOBALMART;

USE GLOBALMART;

CREATE TABLE PRODUCT 
(
	ID INT(10) unsigned NOT NULL, 
	NAME VARCHAR(255) NOT NULL, 
	TYPE VARCHAR(255) NOT NULL, 
	PRICE DOUBLE(10) NOT NULL, 
	PRIMARY KEY (ID)
);


INSERT INTO PRODUCT VALUES (1,'A','alpha',10);
INSERT INTO PRODUCT VALUES (2,'B','alpha',11);
INSERT INTO PRODUCT VALUES (3,'C','beta',12);
